'use client';
import { useEffect,useMemo,useState } from 'react';
import dynamic from 'next/dynamic';
import { pairTarget as p } from '@/data/pairTarget';
const Editor=dynamic(()=>import('@monaco-editor/react'),{ssr:false});
const steps=['Understand','Approach','Plan','Code','Reflect'];
type Frame={i:number;value:number;needed:number;seen:Record<number,number>;line:number;found?:number[]};
function makeTrace(values:number[],target:number){const seen:Record<number,number>={};const out:Frame[]=[];for(let i=0;i<values.length;i++){const value=values[i],needed=target-value;out.push({i,value,needed,seen:{...seen},line:4});out.push({i,value,needed,seen:{...seen},line:5});if(seen[needed]!==undefined){out.push({i,value,needed,seen:{...seen},line:6,found:[seen[needed],i]});break}seen[value]=i;out.push({i,value,needed,seen:{...seen},line:7})}return out}
export function LearningWorkspace(){const [stage,setStage]=useState(0),[q,setQ]=useState(0),[feedback,setFeedback]=useState(''),[code,setCode]=useState(p.starterCode.python),[order,setOrder]=useState(()=>[p.planSteps[1],p.planSteps[3],p.planSteps[0],p.planSteps[4],p.planSteps[2]]),[frame,setFrame]=useState(0),[playing,setPlaying]=useState(false),[hint,setHint]=useState(0),[reflection,setReflection]=useState('');const trace=useMemo(()=>makeTrace([4,7,1,9],8),[]);const current=trace[frame];
useEffect(()=>{if(!playing)return;const id=setInterval(()=>setFrame(f=>{if(f>=trace.length-1){setPlaying(false);return f}return f+1}),700);return()=>clearInterval(id)},[playing,trace.length]);
const questions=stage===0?p.understanding:p.approach;function answer(index:number){const o=questions[q].options[index];setFeedback(o.feedback+(o.complexity?` Time ${o.complexity.time} · Space ${o.complexity.space}.`:''));if(o.correct)setTimeout(()=>{setFeedback('');if(q<questions.length-1)setQ(q+1);else{setStage(stage+1);setQ(0)}},700)}function move(i:number,d:number){const n=[...order],j=i+d;if(j<0||j>=n.length)return;[n[i],n[j]]=[n[j],n[i]];setOrder(n)}const planGood=order.every((x,i)=>x.id===p.planSteps[i].id);
return <main className="min-h-screen bg-ink grid-bg"><header className="h-16 border-b border-line bg-ink/90 px-6 flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-lg bg-mint text-ink font-black grid place-items-center">T</div><b className="text-lg">ThinkFirst</b><span className="text-xs text-muted border-l border-line pl-3">Arrays & Hashing</span></div><div className="flex gap-5 text-sm text-muted"><span>🔥 3 day streak</span><span>1 / 4</span></div></header>
<div className="max-w-[1500px] mx-auto px-5 py-5"><nav className="flex items-center justify-center mb-6">{steps.map((s,i)=><div className="flex items-center" key={s}><button onClick={()=>i<stage&&setStage(i)} className={`flex items-center gap-2 text-xs font-semibold ${i<=stage?'text-white':'text-muted'}`}><span className={`grid place-items-center w-7 h-7 rounded-full border ${i<stage?'bg-mint border-mint text-ink':i===stage?'border-mint text-mint':'border-line'}`}>{i<stage?'✓':i+1}</span>{s}</button>{i<4&&<div className={`w-12 lg:w-24 h-px mx-3 ${i<stage?'bg-mint':'bg-line'}`}/>}</div>)}</nav>
<div className="flex items-center justify-between mb-4"><div><div className="flex gap-2 items-center text-xs"><span className="text-mint">{p.pattern}</span><span className="text-muted">/</span><span className="text-purple">{p.difficulty}</span></div><h1 className="text-2xl font-bold mt-1">{p.title}</h1></div><button onClick={()=>{if(hint<3||confirm('Are you sure? Try stepping through your code once more first.'))setHint(Math.min(4,hint+1))}} className="px-4 py-2 border border-line rounded-lg text-sm hover:border-purple">💡 Hint {hint}/4</button></div>
{hint>0&&<div className="mb-4 border border-purple/40 bg-purple/10 rounded-xl p-3 text-sm"><b className="text-purple">{p.hints[hint-1].title}: </b><span className="whitespace-pre-wrap">{p.hints[hint-1].content}</span></div>}
{stage<2&&<section className="grid md:grid-cols-[1fr_1.1fr] gap-5"><Card title="The challenge"><p className="text-sm text-slate-300 leading-6">{p.statement}</p><div className="mt-5 space-y-3">{p.examples.map((e,i)=><div key={i} className="bg-ink rounded-lg p-3 font-mono text-xs border border-line"><span className="text-muted">Input </span>{e.input}<br/><span className="text-muted">Output </span><span className="text-mint">{e.output}</span></div>)}</div></Card><Card title={stage===0?'Check your understanding':'Choose your strategy'}><div className="text-xs text-mint mb-3">QUESTION {q+1} OF {questions.length}</div><h2 className="text-xl font-semibold mb-5">{questions[q].prompt}</h2><div className="space-y-2">{questions[q].options.map((o,i)=><button key={o.id} onClick={()=>answer(i)} className="w-full text-left px-4 py-3 rounded-lg border border-line hover:border-mint hover:bg-mint/5 text-sm"><span className="text-muted mr-3">{String.fromCharCode(65+i)}</span>{o.label}{o.complexity&&<span className="float-right text-xs text-muted">{o.complexity.time}</span>}</button>)}</div>{feedback&&<div className="mt-4 p-3 bg-slate-800 rounded-lg text-sm text-slate-300">{feedback}</div>}{stage===1&&feedback&&<SlowPreview/>}</Card></section>}
{stage===2&&<Card title="Put your plan in order"><p className="text-sm text-muted mb-5">Reason it through before the editor unlocks. Move each action into the order your program should follow.</p><div className="max-w-2xl space-y-2">{order.map((x,i)=><div key={x.id} className="flex items-center gap-3 bg-ink border border-line rounded-lg p-3"><span className="text-muted">⠿</span><span className="flex-1 text-sm">{x.text}</span><button onClick={()=>move(i,-1)}>↑</button><button onClick={()=>move(i,1)}>↓</button></div>)}</div><button onClick={()=>planGood?setStage(3):setFeedback('Think about what must exist before you can visit and look up values.')} className="mt-5 bg-mint text-ink font-bold px-5 py-2.5 rounded-lg">Validate my plan →</button>{feedback&&<p className="mt-3 text-sm text-amber-300">{feedback}</p>}</Card>}
{stage===3&&<section className="grid lg:grid-cols-[.7fr_1.15fr_1fr] gap-3 h-[610px]"><Card title="Problem & plan"><p className="text-sm text-slate-300 mb-4">Find two distinct entries totaling the target.</p>{p.planSteps.map((s,i)=><p className="text-xs text-muted py-2 border-t border-line" key={s.id}><span className="text-mint mr-2">{i+1}</span>{s.text}</p>)}<button onClick={()=>setStage(4)} className="mt-5 w-full border border-mint text-mint rounded-lg py-2 text-sm">Tests pass — reflect →</button></Card><div className="border border-line rounded-xl overflow-hidden bg-panel flex flex-col"><div className="h-12 px-4 flex items-center justify-between border-b border-line"><span className="text-sm font-semibold">solution.py</span><button onClick={()=>{setFrame(0);setPlaying(true)}} className="bg-mint text-ink font-bold text-xs px-4 py-2 rounded-md">▶ Run <kbd className="opacity-60 ml-1">⌘↵</kbd></button></div><div className="flex-1"><Editor language="python" theme="vs-dark" value={code} onChange={v=>setCode(v||'')} options={{minimap:{enabled:false},fontSize:13,lineHeight:22,padding:{top:14},glyphMargin:false,lineNumbersMinChars:3}}/></div><div className="p-2 border-t border-line text-xs text-mint">✓ Example trace ready · {trace.length} events</div></div><Visualizer frame={current} index={frame} total={trace.length} playing={playing} setPlaying={setPlaying} setFrame={setFrame}/></section>}
{stage===4&&<Card title="Teach it back"><p className="text-muted text-sm mb-3">In 2–3 sentences, explain why the map lets you avoid checking every pair.</p><textarea value={reflection} onChange={e=>setReflection(e.target.value)} rows={5} className="w-full bg-ink border border-line rounded-lg p-4 outline-none focus:border-mint" placeholder="I scan once because…"/><p className="text-xs text-muted mt-2">{reflection.length}/80 characters needed</p><button disabled={reflection.length<80} className="mt-5 bg-mint disabled:opacity-30 text-ink font-bold px-5 py-2.5 rounded-lg">Complete reflection</button></Card>}</div></main>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <div className="bg-panel border border-line rounded-xl p-5 overflow-auto scrollbar"><h3 className="font-semibold mb-4">{title}</h3>{children}</div>}
function SlowPreview(){return <div className="mt-4 flex gap-2">{[4,7,1,9].map((n,i)=><div key={i} className={`w-10 h-10 border rounded grid place-items-center text-sm ${i<2?'border-amber-400 bg-amber-400/10':'border-line'}`}>{n}</div>)}<span className="text-xs text-muted self-center ml-2">Comparisons multiply: 1, 2, 3…</span></div>}
function Visualizer({frame,index,total,playing,setPlaying,setFrame}:{frame:Frame;index:number;total:number;playing:boolean;setPlaying:(v:boolean)=>void;setFrame:(v:number|((x:number)=>number))=>void}){const values=[4,7,1,9];return <div className="bg-panel border border-line rounded-xl overflow-hidden flex flex-col"><div className="p-4 border-b border-line flex justify-between"><b className="text-sm">Live memory</b><span className="text-xs text-mint">line {frame.line}</span></div><div className="p-5 flex-1"><p className="text-xs text-muted mb-7">ARRAY · values</p><div className="flex gap-2">{values.map((v,i)=><div key={i} className="text-center"><div className={`w-11 h-11 rounded-lg border grid place-items-center font-mono transition ${i===frame.i?'border-mint bg-mint/10 shadow-[0_0_18px_#5ee9b533]':'border-line'}`}>{v}</div><span className="text-[10px] text-muted">{i}</span>{i===frame.i&&<div className="text-[10px] text-mint mt-1">▲ i</div>}</div>)}</div><p className="text-xs text-muted mt-10 mb-3">HASH MAP · seen</p><div className="border border-line rounded-lg overflow-hidden"><div className="grid grid-cols-2 bg-ink text-xs text-muted p-2"><span>VALUE</span><span>INDEX</span></div>{Object.entries(frame.seen).map(([k,v])=><div className="grid grid-cols-2 p-2 border-t border-line font-mono text-sm flash" key={k}><span className="text-purple">{k}</span><span>{v}</span></div>)}{!Object.keys(frame.seen).length&&<div className="p-4 text-center text-xs text-muted">Empty — for now</div>}</div><div className="mt-5 grid grid-cols-3 gap-2 text-xs"><Metric k="value" v={frame.value}/><Metric k="needed" v={frame.needed}/><Metric k="i" v={frame.i}/></div>{frame.found&&<div className="mt-4 p-3 bg-mint/10 border border-mint/40 rounded-lg text-sm text-mint">Pair found: [{frame.found.join(', ')}]</div>}</div><div className="border-t border-line p-3"><div className="h-1 bg-line rounded mb-3"><div className="h-full bg-mint rounded" style={{width:`${(index+1)/total*100}%`}}/></div><div className="flex justify-center gap-2"><button onClick={()=>setFrame(0)}>↺</button><button onClick={()=>setFrame(x=>Math.max(0,x-1))} className="px-3">◀</button><button onClick={()=>setPlaying(!playing)} className="w-9 h-9 rounded-full bg-white text-ink">{playing?'Ⅱ':'▶'}</button><button onClick={()=>setFrame(x=>Math.min(total-1,x+1))} className="px-3">▶</button></div></div></div>}
function Metric({k,v}:{k:string;v:number}){return <div className="bg-ink rounded p-2"><div className="text-muted">{k}</div><div className="font-mono text-white mt-1">{v}</div></div>}
